# Generated by Django 6.0.5 on 2026-07-27 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Quintal, Libra, Litro, Hora, Unidad, Proyecto', max_length=50, unique=True)),
                ('abreviatura', models.CharField(help_text='Ej: qq, lb, L, hr, ud', max_length=10)),
                ('es_fraccionable', models.BooleanField(default=False, help_text='¿Se puede vender en decimales? (Ej. 1.5 libras = True, 1 Martillo = False)')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Consultoría Contable', max_length=200)),
                ('descripcion', models.TextField(help_text='Detalles del servicio.')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock_disponible', models.PositiveIntegerField(default=0, null=True)),
                ('foto_portada', models.URLField(blank=True, help_text='Foto principal para la lista', null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador (No publicado)'), ('activo', 'Activo (Visible en el directorio)'), ('en_revision', 'En Revisión (Control de calidad por admin)'), ('disponible', 'Disponible (Activo y visible)'), ('oculto', 'Oculto (Retirado por infracción)')], default='borrador', help_text='Estado actual de disponibilidad en el directorio.', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='comercios.perfilnegocio')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.unidadmedida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-estado', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='GaleriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.URLField()),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Vista lateral, Empaque', max_length=50)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_extra', to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_portada', models.URLField(blank=True, help_text='Foto principal para la lista', null=True)),
                ('nombre', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.CharField(blank=True, help_text='Descripcion del servicio', max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador (No publicado)'), ('pausado', 'Pausado (El freelancer/proveedor no está aceptando trabajos)'), ('oculto', 'Oculto (Retirado por infracción)'), ('en_revision', 'En Revisión (Control de calidad por admin)')], default='borrador', help_text='Estado actual de disponibilidad en el directorio.', max_length=20)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='comercios.perfilnegocio')),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.URLField()),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Vista lateral, Empaque', max_length=50)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_extra', to='inventario.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_recompensa', models.PositiveIntegerField(default=0, help_text='Puntos que gana el usuario al comprar esto')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('oculto', 'Oculto')], default='activo', max_length=20)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_catalogo', to='comercios.sucursal')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.servicio')),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogos',
                'constraints': [models.UniqueConstraint(condition=models.Q(('producto__isnull', False)), fields=('sucursal', 'producto'), name='unique_producto_por_sucursal'), models.UniqueConstraint(condition=models.Q(('servicio__isnull', False)), fields=('sucursal', 'servicio'), name='unique_servicio_por_sucursal')],
            },
        ),
    ]
