# Generated by Django 6.0.5 on 2026-06-20 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='usuarios.departamento')),
            ],
            options={
                'unique_together': {('nombre', 'departamento')},
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('NB', 'No binario'), ('O', 'Otro'), ('PND', 'Prefiero no decirlo')], default='PND', help_text='Identidad de género del usuario.', max_length=3)),
                ('estado', models.CharField(choices=[('REV', 'En revisión'), ('ACT', 'Activo'), ('INA', 'Inactivo'), ('SUS', 'Suspendido')], default='REV', help_text='Estado de operatividad y visibilidad de la cuenta.', max_length=3)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.municipio')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil del usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
                'ordering': ['usuario'],
            },
        ),
    ]
