# Generated by Django 6.0.5 on 2026-07-23 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DispositivoTOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secreto', models.CharField(max_length=32)),
                ('confirmado', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='usuarios.departamento')),
            ],
            options={
                'unique_together': {('nombre', 'departamento')},
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('documento_identidad', models.FileField(blank=True, help_text='Opcional al crear el perfil. Obligatorio antes de que un Administrador pueda aprobar.', null=True, upload_to='verificaciones/')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('NB', 'No binario'), ('O', 'Otro'), ('PND', 'Prefiero no decirlo')], default='PND', help_text='Identidad de género del usuario.', max_length=3)),
                ('estado', models.CharField(choices=[('REV', 'En revisión'), ('ACT', 'Activo'), ('INA', 'Inactivo'), ('SUS', 'Suspendido')], default='REV', help_text='Estado de operatividad y visibilidad de la cuenta.', max_length=3)),
                ('estado_verificacion', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('verificado', 'Verificado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.CharField(blank=True, default='', max_length=255)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.municipio')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('verificado_por', models.ForeignKey(blank=True, help_text='Administrador que revisó este perfil', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_verificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil del usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
                'ordering': ['usuario'],
            },
        ),
    ]
