# Generated by Django 6.0.5 on 2026-06-23 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.municipio'),
        ),
    ]
