# Generated by Django 6.0.5 on 2026-07-09 20:28

from django.db import migrations


GRUPOS_BASE = ['Usuario Comun', 'Proveedor', 'Emprendedor', 'Administrador']

def crear_grupos(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for nombre in GRUPOS_BASE:
        Group.objects.get_or_create(name=nombre)

def eliminar_grupos(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=GRUPOS_BASE).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('usuarios', '0001_initial'),  
    ]
    operations = [
        migrations.RunPython(crear_grupos, eliminar_grupos),
    ]