# Generated by Django 6.0.5 on 2026-07-09 21:56

from django.db import migrations


def asignar_permisos(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    PerfilUsuario = apps.get_model('usuarios', 'PerfilUsuario')

    content_type = ContentType.objects.get_for_model(PerfilUsuario)

    administrador = Group.objects.get(name='Administrador')
    permisos = Permission.objects.filter(
        content_type=content_type,
        codename__in=['view_perfilusuario', 'change_perfilusuario']
    )
    administrador.permissions.set(permisos)


def revertir(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    administrador = Group.objects.get(name='Administrador')
    administrador.permissions.clear()


class Migration(migrations.Migration):
    dependencies = [
        ('usuarios', '0002_crear_grupos_base'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]
    operations = [
        migrations.RunPython(asignar_permisos, revertir),
    ]