# Generated by Django 6.0.5 on 2026-06-20 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercios', '0001_initial'),
        ('inventario', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente de Respuesta'), ('RES', 'Respondida por Proveedor'), ('ACE', 'Aceptada por Cliente'), ('REC', 'Rechazada / Cancelada'), ('EXP', 'Vencida por Fecha')], default='PEN', max_length=3)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('valida_hasta', models.DateTimeField(blank=True, help_text='Fecha límite antes de que el precio sufra volatilidad', null=True)),
                ('notas_comprador', models.TextField(blank=True, help_text='Ej: Necesito transporte al mercado central')),
                ('notas_proveedor', models.TextField(blank=True, help_text='Ej: Precio especial por pago de contado')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_recibidas', to='comercios.sucursal')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_pedidas', to='usuarios.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario_ofertado', models.DecimalField(blank=True, decimal_places=2, help_text='Precio final asignado por el proveedor', max_digits=12, null=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transacciones.cotizacion')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, help_text='Cuerpo del mensaje', null=True)),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Formatos permitidos: PDF, JPG, PNG, etc.', null=True, upload_to='cotizaciones/mensajes_adjuntos/')),
                ('leido', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='transacciones.cotizacion')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_enviados', to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Mensaje de Cotización',
                'verbose_name_plural': 'Mensajes de Cotización',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente de confirmación'), ('ACE', 'En preparación'), ('CAM', 'En camino / Delivery'), ('ENT', 'Entregado y Finalizado'), ('CAN', 'Cancelado')], default='PEN', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('total_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_puntos_obtenidos', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True, null=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_recibidos', to='comercios.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_realizados', to='usuarios.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('COM', 'Ganancia por compra en sucursal'), ('BON', 'Bono (Bienvenida, Referido, etc.)'), ('CAN', 'Canjeo de recompensa'), ('EXP', 'Expiración por inactividad'), ('PEN', 'Penalización / Reembolso')], max_length=3)),
                ('cantidad', models.IntegerField(help_text='Usa números positivos para ganancias y negativos para gastos/canjes')),
                ('fecha_agregacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(help_text='Ej: Canje por 1 Libra de Frijoles en Pulpería Doña María', max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_puntos', to='usuarios.perfilusuario')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puntos_generados', to='transacciones.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario_historico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('puntos_unitarios_historicos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('item_catalogo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.catalogo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transacciones.pedido')),
            ],
        ),
    ]
