# Generated by Django 6.0.5 on 2026-07-27 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubroPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre general del rubro (Ej. Agricultura)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Breve explicación de qué abarca este rubro.')),
                ('icono', models.CharField(blank=True, default='', help_text="Clase del ícono para el Frontend (Ej. 'fa-solid fa-tractor')", max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar si este rubro ya no está disponible en la plataforma')),
            ],
            options={
                'verbose_name': 'Rubro Principal',
                'verbose_name_plural': 'Rubros Principales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SubRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rubro_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrubros', to='comercios.rubroprincipal')),
            ],
            options={
                'verbose_name': 'Sub Rubro',
                'verbose_name_plural': 'Sub Rubros',
                'ordering': ['rubro_padre__nombre', 'nombre'],
                'unique_together': {('rubro_padre', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='PerfilNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del negocio', max_length=50)),
                ('razon_social', models.CharField(blank=True, default='', max_length=200)),
                ('ruc', models.CharField(blank=True, default='', max_length=50)),
                ('url_documento_legal', models.URLField(blank=True, default='', max_length=300)),
                ('estado', models.CharField(choices=[('en_revision', 'En Revisión (Pendiente de validación)'), ('activo', 'Activo (Visible en el directorio)'), ('inactivo', 'Inactivo (Pausado por el dueño)'), ('suspendido', 'Suspendido (Por infracciones o reportes)')], db_index=True, default='en_revision', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('perfil_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negocios', to='usuarios.perfilusuario')),
                ('sub_rubro', models.ForeignKey(help_text='Selecciona la categoría específica del negocio.', on_delete=django.db.models.deletion.PROTECT, related_name='negocios', to='comercios.subrubro')),
            ],
            options={
                'verbose_name': 'Perfil de Negocio',
                'verbose_name_plural': 'Perfiles de Negocio',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_presencia', models.CharField(choices=[('FIS', 'Local Físico (Visitable)'), ('VIR', 'Solo a Domicilio / Virtual / Freelancer')], default='FIS', max_length=3)),
                ('nombre', models.CharField(help_text="Ej: Sucursal Centro, o 'Servicios a Domicilio'", max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estado', models.CharField(choices=[('en_revision', 'En Revisión (Pendiente de validación)'), ('activo', 'Activo (Visible en el directorio)'), ('inactivo', 'Inactivo (Pausado por el dueño)'), ('suspendido', 'Suspendido (Por infracciones o reportes)')], db_index=True, default='en_revision', max_length=20)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='comercios.perfilnegocio')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='ContactoSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre del encargado del numero.', max_length=50)),
                ('tipo_contacto', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telefono', 'Telefono')], default='telefono', help_text='Tipo de contacto.', max_length=20)),
                ('telefono', models.CharField(max_length=12)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercios.sucursal')),
            ],
        ),
        migrations.AddIndex(
            model_name='perfilnegocio',
            index=models.Index(fields=['estado', 'sub_rubro'], name='comercios_p_estado_2bf2ed_idx'),
        ),
    ]
