# Generated by Django 6.0.5 on 2026-07-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='estado',
            field=models.CharField(choices=[('en_revision', 'En Revisión (Pendiente de validación)'), ('activo', 'Activo (Visible en el directorio)'), ('inactivo', 'Inactivo (Pausado por el dueño)'), ('suspendido', 'Suspendido (Por infracciones o reportes)')], db_index=True, default='en_revision', max_length=20),
        ),
    ]
